defaults:
  - whisper_baseline
  - _self_
  - override backend: onnxruntime

hydra:
  sweeper:
    params:
      backend.auto_optimization: null,O1,O2,O3,O4

experiment_name: whisper_auto_opt(${backend.auto_optimization})

backend:
  no_weights: false
  use_cache: true
  use_merged: false