defaults:
  - backend: pytorch # default backend
  - benchmark: inference # default benchmark
  - experiment # inheriting from experiment config
  - _self_ # for hydra 1.1 compatibility
  - override hydra/job_logging: colorlog # colorful logging
  - override hydra/hydra_logging: colorlog # colorful logging

# for whisper experiments I would like to separate them based
# on device + backend + batch size + new tokens
hydra:
  run:
    dir: experiments/${device}_${backend.name}_${benchmark.input_shapes.batch_size}_${benchmark.new_tokens}/${experiment_name}
  sweep:
    dir: experiments/${device}_${backend.name}_${benchmark.input_shapes.batch_size}_${benchmark.new_tokens}/${experiment_name}
  job:
    chdir: true # to change the working directory during the run/sweep directory
  sweeper:
    params:
      benchmark.new_tokens: 10,100
      benchmark.input_shapes.batch_size: 64,128

experiment_name: whisper_baseline
model: openai/whisper-base

backend:
  no_weights: false
  initial_isolation_check: false
  continous_isolation_check: false
