# This is a base config file that can potentially be used for all experiments
defaults:
  - backend: pytorch # default backend
  - benchmark: training # default benchmark
  - experiment # inheriting experiment schema
  - _self_ # for hydra 1.1 compatibility
  - override hydra/job_logging: colorlog # colorful logging
  - override hydra/hydra_logging: colorlog # colorful logging
  - override hydra/launcher: joblib

# hydra behavior configuration
hydra:
  run:
    dir: examples/training-llamas/experiments # where to save the experiment's output
  sweep:
    dir: examples/training-llamas/experiments # where to save the experiment's output
  job:
    chdir: true # to change the working directory during the run/sweep directory
    env_set:
      CUDA_VISIBLE_DEVICES: 0
  launcher:
    n_jobs: 2
    prefer: processes # use processes instead of threads
    backend: multiprocessing # use multiprocessing backend instead of loky
  sweeper:
    max_batch_size: 1
