defaults:
  - _base_
  - _self_

experiment_name: awq+gemm-batch_size(${benchmark.input_shapes.batch_size})-sequence_length(${benchmark.input_shapes.sequence_length})-new_tokens(${benchmark.new_tokens})
model: IlyasMoutawwakil/vicuna-7b-v1.5-awq-gemm
