defaults:
  - hydra_base # inherits from base config
  - _self_ # for hydra 1.1 compatibility
  - override backend: neural_compressor # override backend to openvino

experiment_name: neural_compressor_bert

model: distilbert-base-uncased-finetuned-sst-2-english
device: cpu

backend:
  quantization: true
  quantization_config:
    approach: static

benchmark:
  input_shapes:
    batch_size: 8
    sequence_length: 512