defaults:
  - hydra_base # inherits from base config
  - _self_ # for hydra 1.1 compatibility
  - override backend: onnxruntime # override backend to onnxruntime

experiment_name: onnxruntime_bert

model: distilbert-base-uncased-finetuned-sst-2-english
device: cpu

backend:
  auto_optimization: O1
  auto_quantization: arm64
  auto_quantization_config:
    is_static: true
    per_channel: false
  
  calibration: true
  # use_merged: true
  # no_weights: true

benchmark:
  input_shapes:
    batch_size: 1
    sequence_length: 1