defaults:
  - hydra_base # inherits from base config
  - _self_ # for hydra 1.1 compatibility
  - override backend: openvino # override backend to openvino

experiment_name: openvino_bert

model: distilbert-base-uncased-finetuned-sst-2-english
device: cpu

backend:
  reshape: true
  half: true

  quantization: true

benchmark:
  input_shapes:
    batch_size: 8
    sequence_length: 512