defaults:
  - hydra_base # inherits from base config
  - _self_ # for hydra 1.1 compatibility

experiment_name: pytorch_bert

model: decapoda-research/llama-7b-hf
device: cuda:2

backend:
  delete_cache: true
  torch_dtype: float16
  no_weights: true
  load_in_8bit: true

benchmark:
  memory: true
  input_shapes:
    batch_size: 1
    sequence_length: 1
  
  new_tokens: 100