_target_: src.backend.onnxruntime.ORTBackend

name: onnxruntime
version: ${onnxruntime_version:}

use_io_binding: false
inter_op_num_threads: null
intra_op_num_threads: null

auto_optimization_level: null
auto_optimization_config:
  optimization_level: null
  optimize_for_gpu: null
  fp16: null
  enable_transformers_specific_optimizations: null
  disable_gelu_fusion: null
  disable_layer_norm_fusion: null
  disable_attention_fusion: null
  disable_skip_layer_norm_fusion: null
  disable_bias_skip_layer_norm_fusion: null
  disable_bias_gelu_fusion: null
  disable_embed_layer_norm_fusion: null
  enable_gelu_approximation: null
  use_mask_index: null
  no_attention_mask: null
  disable_shape_inference: null

auto_quantization_strategy: null
auto_quantization_config:
  is_static: null
  use_symmetric_activations: null
  use_symmetric_weights: null
  per_channel: null
  nodes_to_quantize: null
  nodes_to_exclude: null
  operators_to_quantize: null
