_target_: src.backends.onnxruntime.ORTBackend

name: onnxruntime
version: ${onnxruntime_version:}

device: cpu
inference: true
inter_op_num_threads: null
intra_op_num_threads: null

optimization_level: 1
enable_transformers_specific_optimizations: true
optimize_for_gpu: false