_target_: src.backend.onnxruntime.ORTBackend

name: onnxruntime
version: ${onnxruntime_version:}

use_io_binding: false
provider: ${infer_provider:${device}}
inter_op_num_threads: null
intra_op_num_threads: null

# main optimizations: O1, O2, O3, O4.
optimization_level: null
# additional optimization configs, for example:
optimization_parameters:
  optimize_for_gpu: null
  fp16: null
  enable_transformers_specific_optimizations: null
  disable_gelu_fusion: null
  disable_layer_norm_fusion: null
  disable_attention_fusion: null
  disable_skip_layer_norm_fusion: null
  disable_bias_skip_layer_norm_fusion: null
  disable_bias_gelu_fusion: null
  disable_embed_layer_norm_fusion: null
  enable_gelu_approximation: null
  use_mask_index: null
  no_attention_mask: null
  disable_shape_inference: null

# main quantization strategies: arm64, avx2, avx512, avx512_vnni, tensorrt.
quantization_strategy: null
# additional optimization configs, for example:
quantization_parameters:
  is_static: null
  use_symmetric_activations: null
  use_symmetric_weights: null
  per_channel: null