_target_: src.backend.pytorch.PyTorchBackend

name: pytorch
version: ${pytorch_version:}

inter_op_num_threads: null
intra_op_num_threads: null

disable_grad: ${is_inference:${benchmark.name}}
eval_mode: ${is_inference:${benchmark.name}}
bettertransformer: false
torch_compile: false
