_target_: src.backend.pytorch.PyTorchBackend

name: pytorch
version: ${pytorch_version:}

device: cpu
inter_op_num_threads: null
intra_op_num_threads: null

optimization:
  bettertransformer: false
  torch_compile: false
  grad_enabled: false
  eval_mode: false