_target_: src.backends.pytorch.PyTorchBackend

name: pytorch
version: ${pytorch_version:}

bettertransformer: true
torch_compile: false
no_grad: true
device: cpu
num_threads: null
num_interops_threads: null