_target_: src.backend.pytorch.PyTorchBackend

name: pytorch
version: ${pytorch_version:}

inter_op_num_threads: null
intra_op_num_threads: null

disable_grad: false
eval_mode: false

optimization:
  bettertransformer: false
  torch_compile: false