_target_: src.backend.pytorch.PyTorchBackend

name: pytorch
version: ${pytorch_version:} # resolved by pytorch config dataclass

inter_op_num_threads: null # for now default to pytorch's default behavior
intra_op_num_threads: null # for now default to pytorch's default behavior

disable_grad: ${is_inference:${benchmark.name}}
eval_mode: ${is_inference:${benchmark.name}}
bettertransformer: false
torch_compile: false
