_target_: src.backends.pytorch.PyTorchBackend

name: pytorch
version: ${pytorch_version:}

device: cpu
inference: true
inter_op_num_threads: null
intra_op_num_threads: null

bettertransformer: true
torch_compile: false
no_grad: true