defaults:
  - backend: pytorch
  - base_benchmark
  - _self_

hydra:
  run:
    dir:
      runs/${experiment_name}/${experiment_id}
  sweep:
    dir: 
      sweeps/${experiment_name}/${experiment_id}
  job:
    chdir: true
    env_set:
      TOKENIZERS_PARALLELISM: "false"

experiment_name: default

model: bert-base-cased

batch_size: 1
sequence_length: 128
sparsity: 0.5

benchmark_duration: 10
warmup_runs: 5