defaults:
  - backend: pytorch
  - base_benchmark
  - _self_
  - override hydra/job_logging: colorlog
  - override hydra/hydra_logging: colorlog

hydra:
  run:
    dir:
      runs/${experiment_name}/${experiment_datetime_id}
  sweep:
    dir: 
      sweeps/${experiment_name}/${experiment_datetime_id}
  job:
    chdir: true
    env_set:
      TOKENIZERS_PARALLELISM: "false"

experiment_name: default

model: bert-base-cased

batch_size: 4
sequence_length: 96
sparsity: 0.5

benchmark_duration: 5
warmup_runs: 5