defaults:
  - backend: pytorch
  - _self_

hydra:
  run:
    dir:
      outputs/${experiment_name}/${experiment_id}
  sweep:
    dir: 
      outputs/${experiment_name}/${experiment_id}/${instance_id}
  job:
    env_set:
      TOKENIZERS_PARALLELISM: "false"

experiment_name: default

model: bert-base-cased

batch_size: 1
sequence_length: 128

benchmark_duration: 5
warmup_runs: 5