defaults:
  - pytorch_text_inference
  - _self_
  - override backend: onnxruntime

hydra:
  sweeper:
    # this will allow hydra to start the sweep fatser instead of 
    # generating and validating all the generated configurations
    max_batch_size: 16
    # search space generates 2^17=131072 configurations
    # so this is just a demonstration of the sweeper capabilities
    params:
      backend.optimization.optimization_level: 0,1,2,99
      backend.optimization.enable_transformers_specific_optimizations: true,false
      backend.optimization.optimize_for_gpu: true,false
      backend.optimization.fp16: true,false
      backend.optimization.disable_gelu_fusion: true,false
      backend.optimization.disable_layer_norm_fusion: true,false
      backend.optimization.disable_attention_fusion: true,false
      backend.optimization.disable_skip_layer_norm_fusion: true,false
      backend.optimization.disable_bias_skip_layer_norm_fusion: true,false
      backend.optimization.disable_bias_gelu_fusion: true,false
      backend.optimization.disable_embed_layer_norm_fusion: true,false
      backend.optimization.enable_gelu_approximation: true,false
      backend.optimization.use_mask_index: true,false
      backend.optimization.no_attention_mask: true,false
      backend.optimization.disable_shape_inference: true,false
      ## experimental options
      # backend.optimization.use_multi_head_attention: true,false
      # backend.optimization.enable_gemm_fast_gelu: true,false
      # backend.optimization.use_raw_attention_mask: true,false
      # backend.optimization.disable_group_norm: true,false
      # backend.optimization.disable_packed_kv: true,false

experiment_name: exhaustive-ort-optimization
