defaults:
  - bert # base config
  - _self_
  - override backend: onnxruntime # group config should be overriden
  - override hydra/sweeper: optuna
  - override hydra/sweeper/sampler: tpe

hydra:
  sweeper:
    # Optuna parameters
    study_name: onnxruntime_optimization_level
    direction: minimize
    n_trials: 30
    n_jobs: 1
    storage: null
    params:
      model: bert-base-uncased
      device: cuda
      backend.use_io_binding: true
      # optimization parameters
      # backend.optimization.level: O4
      # backend.optimization.for_gpu: true
      # backend.optimization.disable_gelu_fusion: true,false
      # backend.optimization.disable_layer_norm_fusion: true,false
      # backend.optimization.disable_attention_fusion: true,false
      # backend.optimization.disable_skip_layer_norm_fusion: true,false
      # backend.optimization.disable_bias_skip_layer_norm_fusion: true,false
      # backend.optimization.disable_bias_gelu_fusion: true
      # backend.optimization.disable_embed_layer_norm_fusion: true,false
      # backend.optimization.use_mask_index: true,false
      # backend.optimization.no_attention_mask: true
      # backend.optimization.disable_shape_inference: true # creates issues with whisper
      # backend.optimization.use_multi_head_attention: true,false
      # backend.optimization.enable_gemm_fast_gelu_fusion: true,false
      # backend.optimization.use_raw_attention_mask: true,false
      # backend.optimization.disable_group_norm_fusion: true,false
      # backend.optimization.disable_packed_kv: false,true

      # quantization parameters
      # backend.quantization.instructions: null
      backend.quantization.is_static: false
      backend.quantization.format: QOperator
      backend.quantization.mode: IntegerOps
      backend.quantization.activations_dtype: QUInt8
      backend.quantization.weights_dtype: QInt8,QUInt8
      backend.quantization.per_channel: true,false
      backend.quantization.reduce_range: true,false
