defaults:
  - base_experiment
  - _self_
  - override backend: onnxruntime
  - override hydra/sweeper: optuna
  - override hydra/sweeper/sampler: tpe

hydra:
  sweeper:
    # Optuna parameters
    study_name: onnxruntime_optimization_level
    direction: minimize
    n_trials: 5
    n_jobs: 1
    storage: null
    params:
      backend.optimization_level: O1,O2,O3,O4
      backend.optimization_parameters.for_gpu: true,false
      backend.optimization_parameters.disable_gelu_fusion: true,false
      backend.optimization_parameters.disable_layer_norm_fusion: true,false
      backend.optimization_parameters.disable_attention_fusion: true,false
      backend.optimization_parameters.disable_skip_layer_norm_fusion: true,false
      backend.optimization_parameters.disable_bias_skip_layer_norm_fusion: true,false
      backend.optimization_parameters.disable_bias_gelu_fusion: true,false
      backend.optimization_parameters.disable_embed_layer_norm_fusion: true,false
      backend.optimization_parameters.use_mask_index: true,false
      backend.optimization_parameters.disable_shape_inference: true,false

experiment_name: optuna-onnxruntime-optimization-level
