name: GPU Unit Tests

on:
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build Docker image
        if: github.event_name == 'push' && (github.event_path | contains('docker/gpu.Dockerfile') || github.event_path | contains('gpu_requirements.txt'))
        run: docker build -f docker/gpu.Dockerfile -t optimum-benchmark-gpu .
      - name: Run Docker container
        run: docker run --rm --gpus all --workdir=/workspace/optimum-benchmark optimum-benchmark-gpu pytest -k "(cuda or tensorrt) and not onnxruntime_training"
