name: GPU OnnxRuntime Training Unit Tests

on:
  pull_request:
    types: [opened, reopened, labeled]

jobs:
  build-and-test:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build GPU OnnxRuntime Training Docker image
        if: github.event_name == 'push' && (contains(github.event_path, 'docker/gpu_onnxruntime_training.Dockerfile') || contains(github.event_path, 'gpu_onnxruntime_training_requirements.txt'))
        run: docker build -f docker/gpu_onnxruntime_training.Dockerfile -t gpu-onnxruntime-training .
      - name: Run GPU OnnxRuntime Training tests
        run:
          docker run --rm --gpus all -v $(pwd):/workspace/optimum-benchmark --workdir=/workspace/optimum-benchmark gpu-onnxruntime-training \
          /bin/bash -c "pip install -r gpu_onnxruntime_training_requirements.txt \
          && pip install -e .[test] \
          && pytest -k '(cuda or tensorrt) and onnxruntime_training'"
