name: GPU OnnxRuntime Training Unit Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build Docker image
        run: docker build -f docker/gpu_onnxruntime_training.Dockerfile -t gpu-onnxruntime-training .
      - name: Run Docker container
        run:
          docker run --rm --gpus all --workdir=/workspace/optimum-benchmark gpu-onnxruntime-training \
          pytest -k "(cuda or tensorrt) and onnxruntime_training"
