name: GPU OnnxRuntime Training Unit Tests

on:
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build Docker image
        if: github.event_name == 'push' && (github.event_path | contains('docker/gpu_onnxruntime_training.Dockerfile'))
        run: docker build -f docker/gpu_onnxruntime_training.Dockerfile -t gpu-onnxruntime-training .
      - name: Run Docker container
        run: sh tests/scripts/gpu_onnxruntime_training.sh
