name: GPU Unit Tests

on:
  pull_request:
    types: [opened, reopened, synchronize]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build-and-test:
    runs-on: self-hosted
    steps:
      - name: Restore docker ownership
        run: sh tests/scripts/restore_ownership.sh

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build GPU Docker image
        if: github.event_name == 'push' && (contains(github.event_path, 'docker/gpu.dockerfile') || contains(github.event_path, 'gpu_requirements.txt'))
        run: docker build -f docker/gpu.dockerfile -t optimum-benchmark-gpu .

      - name: Run GPU tests
        run: |
          docker run
            --rm
            --entrypoint /bin/bash
            --gpus all
            --volume $(pwd):/workspace/optimum-benchmark
            --workdir /workspace/optimum-benchmark
            optimum-benchmark-gpu
            -c "pip install -e .[test] && pytest -k '(cuda or tensorrt) and not onnxruntime_training' -x"
