name: GPU OnnxRuntime Training Unit Tests

on:
  workflow_dispatch:
  schedule:
    - cron: 0 1 */3 * * # at 1am every 3 days
  pull_request:
    types: [opened, synchronize, reopened, labeled]

jobs:
  build-and-test:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build Docker image
        run: docker build -f examples/docker/gpu_onnxruntime_training.Dockerfile -t gpu-onnxruntime-training .
      - name: Run Docker container
        run: docker run --rm --gpus all --workdir=/workspace/optimum-benchmark gpu-onnxruntime-training
