name: GPU Unit Tests

on:
  workflow_dispatch:
  schedule:
    - cron: 0 1 */3 * * # at 1am every 3 days
  pull_request:
    types: [opened, synchronize, reopened, labeled]

jobs:
  build-and-test:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build GPU Docker image
        if: github.event_name == 'push' && (contains(github.event_path, 'docker/gpu.Dockerfile') || contains(github.event_path, 'gpu_requirements.txt'))
        run: docker build -f docker/gpu.Dockerfile -t optimum-benchmark-gpu .
      - name: Run GPU tests
        run:
          docker run --rm --gpus all -v $(pwd):/workspace/optimum-benchmark --workdir=/workspace/optimum-benchmark optimum-benchmark-gpu \
          bash -c "pip install -r gpu_requirements.txt \
          && pip install -e .[test] \
          && pytest -k '(cuda or tensorrt) and not onnxruntime_training'"
